Questions from from [here](https://www.w3resource.com/python-exercises/numpy/basic/index.php)

1. Get NumPy Version & Build Info

Write a Numpy program to get the Numpy version and show the Numpy build configuration.

In [4]:
import numpy as np

print(f"Your NumPy version is {np.__version__}")
print(f"Your Numpy config is:\n{np.__config__}")

Your NumPy version is 2.3.1
Your Numpy config is:
<module 'numpy.__config__' from '/Users/christiancamp/Desktop/Python Practice/practice-env/lib/python3.13/site-packages/numpy/__config__.py'>


Your first attempt was wrong. You needed to use `show_config()` instead:

In [5]:
import numpy as np

print(np.show_config())

{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name"

/Users/christiancamp/Desktop/Python Practice/practice-env/lib/python3.13/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


2. Help for NumPy Add Function

Write a NumPy program to get help with the add function.

In [1]:
import numpy as np

np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

Given solution:

In [2]:
import numpy as np

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

3. Test None are Zero

Write a NumPy program to test whether none of the elements of a given array are zero. 

In [33]:
from numpy import random
import numpy as np

arr = random.randint(10, size=(10))

print(arr)

if False in arr:
    print("Elements of 0 found")
else:
    print("No elements of 0 found")



[9 7 3 6 1 3 6 2 2 8]
No elements of 0 found


Given solution:

In [21]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the original array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

# Reassigning array 'x' to a new array containing elements 0, 1, 2, and 3
x = np.array([0, 1, 2, 3])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the updated array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


# Why This Solution Works

The comments on the solution are a bit misleading to me. The "testing for zero" part is taking advantage of how `0` equates to `False` when faced with boolean logic. The given solution is definitely more all-encompassing.

# The np.all() Function

The np.all function can be used to find conditions in an entire dataset. Here's another example:

In [25]:
# Are all values positive?
np.all(data > 0)

# Are all predictions within valid range?
np.all((predictions >= 0) & (predictions <= 1))

# Do all rows have the expected number of elements?
np.all(np.sum(mask, axis=1) == expected_count)

NameError: name 'data' is not defined

4. Test Any Non-Zero

Write a NumPy program to test if any of the elements of a given array are non-zero.

In [47]:
from numpy import random
import numpy as np

data = random.randint(10, size=(10))
print(data)

print("Test to see if none of the elements in the array are 0")
print(np.all(data))


[8 8 0 1 3 9 4 5 1 4]
Test to see if none of the elements in the array are 0
False


5. Test Finiteness of Elements

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [48]:
import numpy as np

# Creating a NumPy array 'a' containing elements 1, 0, NaN (Not a Number), and infinity
a = np.array([1, 0, np.nan, np.inf])

# Printing the original array 'a'
print("Original array")
print(a)

# Checking the given array 'a' element-wise for finiteness and printing the result
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a)) 

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


Yea that one wasn't necessary to figure out honestly.

7. Test for NaN

Write a NumPy program to test element-wise for NaN of a given array.

In [ ]:
import numpy as np

# creating dataset - need to specify size to get an array
nan_data = np.random.randint(0, 10, size=10).astype(float)  # Creates array of 20 random integers between 0-9
no_nan_data = np.random.randint(0, 10, size=10).astype(float)
# choosing random indexes to put NaN (should be indices, not values from data)
index_nan = np.random.choice(len(data), 3, replace=False)
# adding nan to the data  # Convert to float first, since integers can't hold NaN
nan_data[index_nan] = np.nan 

print(np.isnan(nan_data))
print(np.isnan(no_nan_data))



[ True  True False False  True False False False False False]
[False False False False False False False False False False]


8. Test for Complex/Real/Scalar

Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 

In [30]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'a' containing various types of numbers (complex, real, scalar)
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

# Printing the original array 'a'
print("Original array")
print(a)

# Checking the given array 'a' element-wise for complex numbers and printing the result
print("Checking for complex number:")
print(np.iscomplex(a))

# Checking the given array 'a' element-wise for real numbers and printing the result
print("Checking for real number:")
print(np.isreal(a))

# Checking if a value is a scalar or not (in this case, checking if 3.1 is a scalar)
print("Checking for scalar type:")
print(np.isscalar(3.1))

# Checking if a list ([3.1]) is a scalar or not (in this case, it's not a scalar)
print(np.isscalar([3.1])) 

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


9. Test Element-Wise Tolerance Equality

Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

I didn't even fully understand what they're asking for here so here's the answer with an extensive explanation:

In [31]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Printing the description of the operation being performed
print("Test if two arrays are element-wise equal within a tolerance:")

# Checking if the two arrays are element-wise equal within a tolerance and printing the result
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

# Checking if the arrays with NaN (Not a Number) values are equal while treating NaN as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan]))

# Checking if the arrays with NaN (Not a Number) values are equal considering NaN values as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


# np.allclose()

Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers. The relative difference and the absolute difference are added together to compare against the absolute difference between *a* and *b*.

NaNs are treated as equal if they are in the same place and if `equan_nan=TRUE`. Infs are treated as equal if they are in the same place and of the same sign in both arrays.

Explanation:

In the above exercise -

## print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))

Here the np.allclose() function tests the two arrays `[1e10, 1e-7]` and `[1.00001e10, 1e-8]` are element-wise equal within the default tolerance (relative tolerance `rtol=1e-9`, absolute tolerance `atol=1e-12`). In this case, the two arrays are not considered equal within the given tolerance, so the function returns `False`. 

## print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))

Heres the `np.allclose()` function tests if the two arrays `[1e10, 1e-8]` and `[1.00001e10, 1e-9]` are element-wise equal within the default tolerance. In this case, the two arrays are considered equal within the given tolerance.

## print(np.allclose([1e10,1e-8], [1.0001e10,1e-9])) 

Here `np.allclose()` function tests if the two arrays `[1e10, 1e-8]` and `[1.0001e10, 1e-9]` are element-wise equal within the default tolerance. In this case, the two arrays are not considered equal within the given tolerance, so the function returns False.

## print(np.allclose([1.0, np.nan], [1.0, np.nan]))

Here `np.allclose()` function tests if the two arrays `[1.0, np.nan]` and `[1.0, np.nan]` are element-wise equal within the default tolerance. By default, the function treats NaN values as unequal, so it returns False.

## print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Here the `np.allclose()` function tests if the two arrays `[1.0, np.nan]` and `[1.0, np.nan]` are element-wise equal within the default tolerance. However, this time the `equal_nan=True` parameter is passed, which tells the function to treat NaN values as equal. In this case, the two arrays are considered equal within the given tolerance, so the function returns `True`.

10. Element-Wise Comparison (Greater/Less)

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.



In [32]:
import numpy as np

# Creating NumPy arrays 'x' and 'y' containing numbers for comparison
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(np.greater_equal(x, y))
print(np.less_equal(x, y))

[ True  True  True  True  True  True  True  True  True False]
[ True  True  True  True  True  True  True  True  True  True]


11. Element-Wise Comparison (Equal/Tolerance)

Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [40]:
import numpy as np

# Creating NumPy arrays 'x' and 'y' containing numbers for comparison
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print("Original Numbers:")
print(x)
print(y)

print(f"\nEqual comparison:\n{np.equal(x, y)}\n")
print(f"Equal Tolerance comparison:\n{np.allclose(x, y)}")



Original Numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]

Equal comparison:
[ True  True  True  True  True  True  True  True  True False]

Equal Tolerance comparison:
True


**Explanation**:

At first we declare two arrays: 

`x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])` and

`y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])`.

`print(np.equal(x, y))`: Here, the np.equal() function compares the elements of 'x' and 'y' element-by-element and checks whether they are equal.The function returns a boolean array [True, True, True, True, True, True, True, True, True, False], which is printed to the console. The last element is False because 100 is not exactly equal to 100.000001.

print(np.allclose(x, y)): This line uses the np.allclose() function to check if the two arrays are element-wise equal within a given tolerance (default relative tolerance rtol=1e-9, absolute tolerance atol=1e-12). In this case, the difference between the last elements (100 and 100.000001) is within the default tolerance, so the function returns True.

12. Array Memory Size

Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [59]:
import numpy as np

arr1 = np.array([1, 7, 13, 105])
print(f"Array: {arr1}")
print(f"Number of elements: {arr1.size}")
print(f"Item size of one array element: {arr1.itemsize} byte(s)")
print(f"Memory size of array: {arr1.size * arr1.itemsize} byte(s)")

Array: [  1   7  13 105]
Number of elements: 4
Item size of one array element: 8 byte(s)
Memory size of array: 32 byte(s)


- `size`: This attribute gives the number of elements present in the NumPy array.
- `itemsize`: This attribute gives the memory size of one element of NumPy array in bytes.

13. Create Array of Zeros, Ones, Fives

Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [62]:
import numpy as np

array_zeros = np.zeros(10)
print(f"An array of 10 zeros:\n{array_zeros}\n")

array_ones = np.ones(10)
print(f"An array of 10 ones:\n{array_ones}")

array_fives = np.ones(10)*5
print(f"An array of 10 fives:\n{array_fives}")

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Create Array of Integers 30 to 70

Write a NumPy program to create an array of integers from 30 to 70.

In [64]:
import numpy as np

array_30_to_70 = np.arange(30, 71)
print(array_30_to_70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15. Create Array of Even Integers 30 to 70

Write a NumPy program to create an array of all even integers from 30 to 70.

In [67]:
import numpy as np

array_even_30_to_70 = np.arange(30, 71, 2)
print(array_even_30_to_70)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Create 3x3 Identity Matrix

Write a NumPy program to create a 3x3 identity matrix.

# numpy.identity() in Python

The `numpy.identity()` function is used to create an identity matrix. This is commonly used in linear algebra and numerical computations. It has the following properties:

- Diagonal elements are all 1s.
- Non-diagonal elements are all 0s.

**Syntax:** `numpy.identity(n, dtype=None)`

Where:

- `n`: Takes int value and is dimension n x n of output array.
- `dtype`: Returns the data type of the returned array. It's optional and by default is float.

In [68]:
import numpy as np
from numpy import identity

identity_array = np.identity(3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Generate Random Number [0,1]

Write a NumPy program to generate a random number between 0 and 1.

In [ ]:
import numpy as np
from numpy import random

random_array = np.random.normal(0,1,1)
print(random_array)

[0.53401915]


18. Generate Random Array from Standard Normal

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [79]:
import numpy as np
from numpy import random

random_arr = np.random.normal(0,1,15)
print(random_arr)

[-0.76492872 -0.47857457 -0.58697716 -1.3539459  -0.83867854 -0.8673487
 -0.15508248  3.3766366   0.49104763  0.72232614  0.41616067 -1.17895944
  1.79701514 -1.19796141  0.51003905]


19. Vector 15-55 Without First/Last Values

Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [88]:
from numpy import arange

v = arange(15, 55)
print(f"Original Vector:\n{v}\n")
print(f"New Vector:\n{v[1:-1]}")


Original Vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]

New Vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


20. Create and Iterate 3x4 Array

Write a NumPy program to create a 3X4 array and iterate over it.

In [101]:
import numpy as np

arr = np.arange(10, 22).reshape((3,4))
print(f"Original Array:\n{arr}\n")

print("Each element of the array is:\n")
for x in np.nditer(arr):
    print(x, end=" ")

Original Array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Each element of the array is:

10 11 12 13 14 15 16 17 18 19 20 21 

21. Create Vector of Evenly Spaced Values

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [109]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array 'v' with length 5, evenly distributed values between 10 and 49 using np.linspace()
v = np.linspace(10, 49, 5)

# Printing a message indicating an array of length 5 with values evenly distributed between 10 and 49
print("Length 10 with values evenly distributed between 5 and 50:")

# Printing the array 'v'
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


22. Change Sign of Range 9-15

Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
import numpy as np

# My way
x = np.arange(21)
print(f"Original Vector: {x}\n")

x[9:16] = x[9:16] * -1

print(f"New Vector: {x}\n")

Original Vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

New Vector: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]



In [133]:
import numpy as np

# Their way
x = np.arange(21)
print(f"Original Array: {x}\n")
x[(x >= 9) & (x <= 15)] *= -1
print(f"New Array: {x}")


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

New Array: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Vector of Random Integers [0,10]

Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [145]:
import numpy as np

x = np.random.randint(0, 11, size=5)
print(f"Vector: {x}")

Vector: [8 4 7 3 3]


24. Multiply Two Vectors

Write a NumPy program to multiply the values of two given vectors.

In [148]:
import numpy as np

x = np.array([1, 8, 3, 5])

print(f"Vector-1:\n{x}\n")

y = np.random.randint(0, 11, 4)
print(f"Vector 2:\n{y}\n")

z = x * y
print(f"Vector x multiplied by Vector y:\n{z}")

Vector-1:
[1 8 3 5]

Vector 2:
[ 9  7 10  3]

Vector x multiplied by Vector y:
[ 9 56 30 15]


25. Create 3x4 Matrix (10 to 21)

Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
import numpy as np

# My way

x = np.arange(10, 22)
print(f"Original vector:\n{x}\n")

x = x.reshape(3, 4)
print(f"New 3x4 vector:\n{x}")

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21]

New 3x4 vector:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
# Their way (more direct)

x = np.arange(10, 22).reshape(3, 4)

print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26. Rows & Columns in Matrix

Write a NumPy program to find the number of rows and columns in a given matrix.

In [168]:
import numpy as np

m = np.arange(10, 22).reshape((3, 4))

print(f"Original Matrix:\n{m}\n")

print(f"Matrix Shape:\n{m.shape}")

Original Matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Matrix Shape:
(3, 4)


27. Create 3x3 Identity Matrix

Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [178]:
import numpy as np

# My way

id_matrix = np.identity(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [173]:
import numpy as np

# Their way

id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


`np.identity(3)`

- Always returns a square matrix.
- Only accepts one parameter: the size.
- Always returns `float64` dtype by default.
- More explicit about creating an identity matrix specifically.

`np.eye(3)`

- More flexible: Can create rectangular matrices with `np.eye(N, M)`.
= Can offset the diagonal with the `k` parameter.
- Accepts a `dtype` parameter directly.
- More general-purpose function.