# What is a Random Number?

Random number does not mean a different number every time. Random means something that can not be predicted logically (duh).

# Pseudo Random and True Random

Computers work on programs, and programs are definitive sets of instructions. So, it means there must be an algorithm to generate a random number as well.

If there is a program to generate a random number it can be predicted, thus it's not truly random.

Random numbers generated through an algorithm are called *pseudo random*.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network, etc.

We don't need truly random numbers unless related to security or the basis of the application is the randomness.

For now, we'll use pseudo random numbers.

# Generate Random Number

NumPy offers the `random` module to work with random numbers.

In [1]:
from numpy import random

x = random.randint(100)

print(x)

9


# Generate Random Float

The random module's `rand()` method returns a random float between 0 and 1:

In [2]:
from numpy import random

x = random.rand()

print(x)

0.1366990543038229


# Generate Random Array

In NumPy, we work with arrays. You can use the two methods from the above examples to make random arrays.

## Integers

The `randint()` method takes a `size` parameter where you can specify the shape of an array.

In [3]:
# Generate a 1D array containing 5 random integers from 0 to 100

from numpy import random

x = random.randint(100, size=(5))

print(x)

[78 44  3 61 61]


In [5]:
# Generate a 2D array with 3 rows, each row containing 5 random integers from 0 to 100

from numpy import random

x = random.randint(100, size=(3,5))

print(x)

[[58 71 10 16  0]
 [23 74 38 15 69]
 [95 82 65 50 51]]


# Floats

The `rand()` method also allows you to specify the shape of the array.

In [6]:
# Generate a 1D array containing 5 random floats

from numpy import random

x = random.rand(5)

print(x)

[0.32671016 0.50082293 0.42551658 0.62169436 0.12632345]


In [7]:
# Generate a 2D array with 3 rows, each row containing 5 random numbers

from numpy import random

x = random.rand(3,5)

print(x)

[[0.17110444 0.70232471 0.72069684 0.24142636 0.46100852]
 [0.8494334  0.84654891 0.54842917 0.82602225 0.59098197]
 [0.78738697 0.06718985 0.59504644 0.65738444 0.89178728]]


# Generate Random Number From Array

The `choice()` method allows you to generate a random value based on an array of values.

The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [9]:
from numpy import random

z = random.choice([3,5,7,9])

print(z)

9


The `choice()` method also allows you to return an array of values.

Add a `size` parameter to specify the shape of the array.

In [10]:
# Generate a 2D array that consists of the values in the array parameter (3,5,7,9)

from numpy import random

x = random.choice([3,5,7,9], size=(3,5))

print(x)

[[3 5 7 3 7]
 [9 7 9 7 7]
 [9 9 3 9 3]]
