# Iterating Arrays

If we iterate on a 1-D array it will go through each element one by one.

In [1]:
# Iterate on the elements of the following 1D array

import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


# Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [2]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


To return the actual values (the scalars), we have to iterate the arrays in each dimension:

In [3]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# Iterating 3-D Arrays

In a 3-D array it will go through all the 2-D arrays.

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values (the scalars), we have to iterate the arrays in each dimension:

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

The function `nditer()` is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues faced in iteration.

## Iterating on Each Scalar Element

In basic `for` loops, iterating through each scalar of an array requires the use of *n* `for` loops which can be difficult to write for arrays with very high dimensionality.

In [6]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

We can use the `op_dtypes` argument and pass the expected datatype to change the datatype of elements while iterating.

NumPy doesn't change the data type of the element in-place, so it needs some other space to perform this action. That extra space is called a buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

In [7]:
import numpy as np

arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


# Iterating With Different Step Size

We can use filtering followed by iteration.

Iterate through every scalar element of the 2D array skipping 1 element:

In [8]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

Sometimes when you're iterating through an array, you need to know not just the value, but also WHERE that value is located (its index/position).

In [ ]:
# Enumerate on the following 1D array elements

import numpy as np

arr = np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
# Enumerate on the following 2D array elements

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
