# Sorting Arrays

Sorting means... well I'm sure you know what it means.

*Ordered sequence* means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending, or descending.

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [1]:
# Sort the array

import numpy as np

arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


**Note:** This method returns a copy of the array, leaving the original array unchanged.

You can also sort arrays of strings, or any other data type:

In [2]:
# Sort alphabetically

import numpy as np

arr = np.array(["banana", "cherry", "apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [3]:
# Sort by boolean

import numpy as np

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


# Sorting a 2-D Array

If you use the `sort()` method on a 2-D array, both arrays will be sorted:

In [4]:
import numpy as np

arr = np.array([[3,2,4], [5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
