# Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an `ndarray`, we can pass a list, tuple, or any array-like object into the `array()` method and it will be converted into an `ndarray`:

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [3]:
# Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

An array that has 0-D arrays as its elements is called a **uni-dimensional or 1-D array**.

These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix of 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`.