# Slicing Arrays

Slicing in Python means taking elements from one given index to another.

We pass slice instead of index like this: `[start:end]`

We can also define the step like this: `[start:end:step]`

If we don't pass start it's considered 0.

If we don't pass end it's the length of the array in that dimension.

If we don't pass step it's considered 1.

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,6,7])

print(arr[1:5])

[2 3 4 5]


**Note:** The result includes the start index, but excludes the end index.

In [3]:
# Slice elements from index 4 to the end of the array

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [4]:
# Slice the elements from the beginning to index 4 (not included)

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


# Negative Slicing

Use the minus operator to refer to an index from the end:

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


# Step

Use the `step` value to determine the step of the slicing:

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]
