# Slicing Arrays

Slicing in Python means taking elements from one given index to another.

We pass slice instead of index like this: `[start:end]`

We can also define the step like this: `[start:end:step]`

If we don't pass start it's considered 0.

If we don't pass end it's the length of the array in that dimension.

If we don't pass step it's considered 1.

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,6,7])

print(arr[1:5])

[2 3 4 5]


**Note:** The result includes the start index, but excludes the end index.

In [3]:
# Slice elements from index 4 to the end of the array

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [4]:
# Slice the elements from the beginning to index 4 (not included)

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


# Negative Slicing

Use the minus operator to refer to an index from the end:

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


# Step

Use the `step` value to determine the step of the slicing:

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


# Slicing 2-D Arrays

From the second element, slice elements from index 1 to index 4 (not included):

In [1]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


From both elements, return index 2:

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2, 2])

[3 8]


From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [3]:
import numpy as np

arr = np.array(([1,2,3,4,5], [6,7,8,9,10]))

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
