# NumPy Data Types

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta 
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

# Checking the Data Type of an Array

The NumPy array object has a property called `dtype` that returns the data type of the array:

In [1]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr.dtype)

int64


# Creating Arrays With a Defined Data Type

We can use the `array()` function to create arrays. This function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements:

In [2]:
# Create an array with the data type string

import numpy as np

arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


For `i`, `u`, `f`, `S` and `U` we can define size as well:

In [3]:
# Create an array with data type 4 bytes integer

import numpy as np

arr = np.array([1,2,3,4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays

The best way to change the data type of an existing array is to make a copy of the array with the `astype()` method.

The `astype()` function creates a copy of the array and allows you to specify the data type as a parameter.

The data type can be specified using a string, like `f` for float, `i` for integer, etc. Or, you can use the data type directly like `float` for float and `int` for integer.

In [4]:
# Change data type from float to integer by using i as parameter

import numpy as np

arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [5]:
# Change data type from float to int by using int as parameter

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64
