# Reshaping Arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping, we can add or remove dimensions or change the number of elements in each dimension.

# Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape from 1-D to 3-D

Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into Any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [23]:
import numpy as np
import inspect

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

try:
    newarr1 = arr.reshape(3, 3)
    print(newarr1)
except ValueError as e:
    print(f"Error: {e}. Skipping...\n")

newarr2 = arr.reshape(2,4)

print(newarr2)

Error: cannot reshape array of size 8 into shape (3,3). Skipping...

[[1 2 3 4]
 [5 6 7 8]]


# Returns Copy or View?

Check if the returned array is a copy or a view:

In [24]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it's a view.

# Unknown Dimension

You are allowed to have one "unknown" dimension.

This means you don't have to specify an exact number for one of the dimensions in the reshape method.

Pass `-1` as the value, and NumPy will calculate this number for you.

In [25]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Note:** We can not pass `-1` to more than one dimension.

# Flattening the Arrays

Flattening an array means converting a multidimensional array into a 1D array.

We can use `reshape(-1)` to do this:

In [26]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**Note:** There are a lot of functions for changing the shapes of arrays in NumPy such as `flatten` and `ravel`. There are also many for rearranging elements such as `rot90`, `flip`, `fliplr`, `flipud`, etc.