# Basic and Advanced Indexing

[Resource](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/BasicIndexing.html)

Indexing into and slicing along the dimensions of an array are known as basic indexing. NumPy also provides a sophisticated system of "advanced indexing", which permits us powerful means for accessing elements of an array that is flexible beyond specifying integers and slices along axes.

For example, we can use advanced indexing to access all of the negative-values elements from `x`.

In [8]:
import numpy as np

x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original Array:\n{x}\n")

# Access the vcolumn-1 of row-0 and row-2
# A 'view' of the underlying data in 'x' is produced; no data is copied
x2 = x[::2, 1] # Starting from the first element going to the end, 
print(f"Indexed Array:\n{x2}\n")

x3= x[x < 0]
print(f"All Negative Elements:\n{x3}")

Original Array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Indexed Array:
[ 2 -3]

All Negative Elements:
[-5 -7 -1 -3 -3]


`x[::2, 1]` checks every two elements (starting with the 0th) and first row.

We will see that, where basic indexing provides us with a *view* of the data within the array without making a copy of it, advanced indexing requires that a copy of the accessed data be made. Here, we will define basic indexing and understand the nuances of working with views of arrays.

# Basic Indexing

## Indexing with Integers and Slice Objects

One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0.

In [25]:
# Accessing the element at ro1-1, last-column of 'x'ArithmeticError
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

print(f"Row-1, last-column of 'x' = {x[1, -1]}\n")

"""
Access the subarray of 'x' contained within the first two rows 
and the first three columns
"""
print(f"First two rows, first three columns of 'x':\n{x[:2, :3]}\n")

"""
NumPy fills in 'trailing' slices if we don't supply as many indices
as there are dimensions in that array.
"""
print(x[0])

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Row-1, last-column of 'x' = 8

First two rows, first three columns of 'x':
[[-5  2  0]
 [-1  9  3]]

[-5  2  0 -7]


Recall that the familiar slicing syntax actually forms `slice` objects "behind the scenes":

In [26]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

# Equivalent to x[:2, :3]
x[slice(None, 2)], slice(None, 3)

(array([[-5,  2,  0, -7],
        [-1,  9,  3,  8]]),
 slice(None, 3, None))

# Using a Tuple as an N-Dimensional Index

According to its definition, we must supply our array-indices as a tuple in order to invoke basic indexing.

As it turns out, we have been forming tuples of indices all along!