One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0.

In [2]:
import numpy as np

x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
Access the column-1 of row-0 and row0-2
This is an example of basic indexing
Creates a 'view' of the underlying data in `x` is produced. No data is copied
"""
print(f"Basic Indexing: Access column-1, row-0, and row-2:\n{x[::2,1]}\n")

"""
An example of advanced indexing
Access all negative elements in `x`
This produces a copy of the accessed data
"""
print(f"Advanced Indexing: Access all negative elements:\n{x[x < 0]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Basic Indexing: Access column-1, row-0, and row-2:
[ 2 -3]

Advanced Indexing: Access all negative elements:
[-5 -7 -1 -3 -3]


We will see that, where basic indexing provides us with a *view* of the data within the array without making a copy of it, advanced indexing requires that a copy of the accessed data be made.

Here, we will define basic indexing and understand the nuances of working with views of arrays.

# Basic Indexing

**Definition:**

Given an *N*-dimensional array, `x`, `x[index]` invokes **basic indexing** whenever `index` is a *tuple* containing any combination of the following types of objects:

- integers
- slice objects
- Ellipsis objects
- numpy.newaxis objects

Accessing the contents of an array via basic indexing **does not create a copy** of those contents. Rather, a "view" of the same underlying data is produced.

## Indexing with Integers and Slice Objects

One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices.

In [3]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
Accessing the element located at row-1, last-column of `x`
"""
print(f"Access the element located at row-1, last-column of `x`:\n{x[1, -1]}\n")

"""
Access the subarray of `x` contained within the first two rows
and the first three columns
"""

print(f"Access the subarray of `x` contained within the first two columns\nand the first three columns:\n{x[:2, :3]}\n")

"""
NumPy fills-in 'trailing' slices if we don't supply as many indices
as there are dimensions in the given array
"""
print(f"Filling-in 'trailing' slices when there are less indices\nthan dimensions in the given array:\n{x[0]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Access the element located at row-1, last-column of `x`:
8

Access the subarray of `x` contained within the first two columns
and the first three columns:
[[-5  2  0]
 [-1  9  3]]

Filling-in 'trailing' slices when there are less indices
than dimensions in the given array:
[-5  2  0 -7]


**Note:** The slice `x[:2, :3]` starts from row and column 0, but **does not** include index 2 and 3.

Also, recall that the *slicing* syntax forms `slice` objects "behind the scenes":

In [4]:
print(x[slice(None, 2), slice(None, 3)])

[[-5  2  0]
 [-1  9  3]]


# Why use slice()?

You use `slice()` for very specific instances when you need variables or dynamic slicing.

Colon Syntax, on the other hand, is concise, readable, and is basically what you'll be using 90% of the time.

# Using a Tuple as an N-dimensional Index

According to its definition, we must supply our array-indices as a tuple in order to invoke basic indexing. As it turns out, we have been forming tuple indices all along!

That is, every time that we index into an array using the syntax `x[i, j, k]`, we are actually forming a *tuple* containing those indices. That is, `x[i, j, k]` us equivalent to `x[(i, j, k )]`.

`x[i, j, k]` forms the tuple `(i, j, k)` and passes that to the array's "get-item" mechanism. Thus, `x[0, 3]` is equivalent to `x[(0, 3)]`.

In [5]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
N-dimensional indexing utilizes tuples:
`x[i, j, k]` is equivalent to `x[(i, j, k)]`
"""
print(f"Tuple result: {x[(1, -2)]}\n")

# equivalent: x[1, -1]
print(f"Indexing result: {x[1, -1]}\n")

# equivalent: x[:2, :3]
print(f"Using slice() method:\n{x[(slice(None, 2), slice(None, 3))]}\n")

# equivalent: x[0]
print(f"Print the first row using a tuple:\n{x[(0,)]}")l

SyntaxError: invalid syntax (540441593.py, line 20)

All objects used in this "get-item" syntax are packed into a tuple. For instance, `x[0, (0, 1)]` is equivalent to `x[(0, (0,1))]`. You may be surprised to find that this is a valid index. However, see that it **does not invoke basic indexing**; the index used here is a tuple that contains an integer and another tuple, which is not permitted by the rules of basic indexing.

Finally, note that the rules of basic indexing specifically call for a *tuple* of indices. Supplying a list of indices triggers advanced indexing rather than basic indexing!

In [ ]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

# Basic indexing specifically requires a tuple
print(f"Basic indexing with a tuple:\n{x[(1, -1)]}\n")

# Indexing with a list triggers advanced indexing
print(f"Advanced indexing with a list:\n{x[[1, -1]]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Basic indexing with a tuple:
8

Advanced indexing with a list:
[[-1  9  3  8]
 [-3 -3  4  6]]


# Ellipsis and Newaxis Objects

The `numpy.newaxis` object can be passed as an index to to an array in order to insert a size-1 dimension into the array.

In [ ]:
print(x.shape)

y = x[np.newaxis, :, :, np.newaxis]
print(y.shape)

# Using the slice method
z = x[(np.newaxis, slice(None), slice(None), np.newaxis)]
print(z.shape)

(3, 4)
(1, 3, 4, 1)
(1, 3, 4, 1)


We can also use the built-in `Elipsis` object in order to insert slices into our index such that the index has as many entries as the array has dimensions. In the same way that `:` can be used to represent a `slice` object, `...` can be used to represent an `Ellipsis` object.

In [ ]:
y = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7]],

              [[ 8,  9, 10, 11],
               [12, 13, 14, 15]],

              [[16, 17, 18, 19],
               [20, 21, 22, 23]]])

# equivalent: `y[:, :, 0]`
print(f"{y[..., 0]}\n")

# using an explicit tuple
print(f"{y[(Ellipsis, 0)]}\n")

# equivalent: `y[0, :, 1]`
print(y[0, ..., 1])

[[ 0  4]
 [ 8 12]
 [16 20]]

[[ 0  4]
 [ 8 12]
 [16 20]]

[1 5]


An index cannot possess more than one `Ellipsis` entry. This can be extremely useful when working with arrays of varying dimensionalities. To access column-0 along all dimensions of an array, `z`, would look like `z[:, 0]` for a 2D array, `z[:, :, 0]` for a 3D array, and so on. 

`z[..., 0]` succinctly encapsulates all iterations of this.

# Producing a View of an Array

As stated above, using basic indexing does not return a copy of the data being accessed. Rather, it produces a *view* of the underlying data. NumPy provides the function `numpy.shares_memory` to determine if two arrays refer to the same underlying data.

In [ ]:
import numpy as np

z = np.array([[ 3.31,  4.71,  0.4 ],
              [ 0.21,  2.85,  3.21],
              [-3.77,  4.53, -1.15]])

# `subarray` is column-0 of `z` via basic indexing
subarray = z[:, 0]
np.shares_memory(subarray, z) # `subarray` is a view of `z`



True

A single number returned by basic indexing does not share memory with the parent array:

In [ ]:
print(z[0,0])
np.shares_memory(z[0, 0], z)

3.31


False

The function `numpy.copy` can be used to create a copy of an array, such that it no longer shares memory with any other array:

In [ ]:
new_subarray = np.copy(subarray)
np.shares_memory(new_subarray, z)

False

Utilizing an array in a mathematical expression involving the arithmetic operators returns an entirely distinct array that does not share memory with the original array:

In [ ]:
np.shares_memory(subarray + 2, subarray)

False

Thus, updating a variable `subarray` via `subarray = subarray + 2` does not overwrite the original data referenced by `np.subarray`.

Rather, `subarray + 2` assigns that new array to the variable `subarray`. NumPy doers provide mechanisms for performing mathematical operations to directly update the underlying data of an array without having to create a distinct array.

# Augmenting the Underlying Data of an Array

Because basic indexing produces a *view* of an array's underlying data, we must take time to understand the ways in which we can augment that underlying data, versus performing operations that produce an array with distinct data. Here we will see that:

- in-place assignments
- augmented assignmenta
- NumPy functions with the `out` argument

can all be used to augment array data in-place.

## In-Place Assignments

The assignment operator, `=`, can be used to update an array's data in-place. Consider the array `a`, and its view `b`:

In [ ]:
a = np.array([0, 1, 2, 3, 4])
b = a[:]

np.shares_memory(a, b)

True

Assigning a new array to `a` simply changes the data that `a` references, divorcing `a` and `b`, leaving `b` unchanged.

In [ ]:
a = np.array([0, -1, -2, -3, -4])
print(a)
print(b)

np.shares_memory(a, b)

[ 0 -1 -2 -3 -4]
[0 1 2 3 4]


False

Performing an assignment on a view of `a`, i.e. `a[:]`, instructs NumPy to perform the assignment to replace `a`'s data in-place:

In [ ]:
a = np.array([0, 1, 2, 3, 4])
b = a[:]
print(np.shares_memory(a, b))

# Assigning an array to a view of `a` causes NumPy to update the data in-place
a[:] = np.array([0, -1, -2, -3, -4])
print(a[:])

# `b` is a view of the same data. Thus, it's affected by this in-place assignment
print(b) 
print(np.shares_memory(a, b))

True
[ 0 -1 -2 -3 -4]
[ 0 -1 -2 -3 -4]
True


The view-assignment mechanism can be used to update a subsection of an array in-place:

In [ ]:
p = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

q = p[0, :]
print(q)

# Assign row-0, column-0, the value -40, and row-0, column-2 the value -50
p[0, ::2] = (-40, -50)
print(p)
print(np.shares_memory(q, p))

# Broadcast=assign -1 to a subsection of `p`
p[1:, 2:] = -1
print(p)
print(np.shares_memory(q, p))

[0 1 2 3]
[[-40   1 -50   3]
 [  4   5   6   7]
 [  8   9  10  11]]
True
[[-40   1 -50   3]
 [  4   5  -1  -1]
 [  8   9  -1  -1]]
True


This view-assignment mechanism can be used to update a subsection of an array in-place:

Again, this updates the underlying data, and thus all views of this data reflect this change.

In [8]:
print(q)

[-40   1 -50   3]


# Augmented Assignments

**Augmented assignment expressions** provide a nice shorthand notation for updating the value of a variable.

For example, the assignment expression `x = x + 5` can be rewritten using the augmented assignment `x += 5`.

While `x += 5` is truly only a shorthand in the context of basic Python objects (integers, floats, etc.), *augmented assignments on NumPy arrays* behave fundamentally different than their long-form counterparts.

Specifically, they directly update the underlying data referenced by the updated array, rather than creating a distinct array, thus affecting any arrays that are views of that data.

Let's take a look:

In [22]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

# `b` and `c` are both views of row-0 of `a`, via basic indexing
b = a[0]
c = a[0]
print(np.shares_memory(a, b) and np.shares_memory(a, c))

# Updating `b` using a mathematical expression creates a distinct array, which is divorced fro `a` and `c`
b = b * -1
print(np.shares_memory(a, b))

# Updating `c` using augmented assignment updates the underlying data that `c` is a view of
c *= -2
print(np.shares_memory(a, c))
# Note that this update is reflected in `a` as well
print(a[0,...])
print(c)


True
False
True
[ 0 -2 -4 -6]
[ 0 -2 -4 -6]


# Specifying out to Perform NumPy Operations In-Place

There is no reason why we should only be able to augment data using arithmetic operations. Indeed, NumPy's various mathematical functions have an optional keyword argument, `out`, which can be used to specify where to "store" the result of the mathematical operation.

By default, the operation will create a distinct array in memory, leaving the input data unaffected.

In [26]:
# `b` is a view of `a`
a = np.array([0., 0.2, 0.4, 0.6, 0.8, 1.])
b = a[:]
print(a)
print(b)
print(np.shares_memory(a, b))

# Specifying `out=a` instructs NumPy to overwrite the data referenced by `a`
np.exp(a, out=a)
print(a)
print(b)

# `b` is still a view of the now-augmented data
print(np.shares_memory(a, b))

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8 1. ]
True
[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]
[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]
True


# Benefits and Risks of Augmenting Data In-Place