# Basic and Advanced Indexing

[Resource](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/BasicIndexing.html)

Indexing into and slicing along the dimensions of an array are known as basic indexing. NumPy also provides a sophisticated system of "advanced indexing", which permits us powerful means for accessing elements of an array that is flexible beyond specifying integers and slices along axes.

For example, we can use advanced indexing to access all of the negative-values elements from `x`.

In [2]:
import numpy as np

x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original Array:\n{x}\n")

# Access the vcolumn-1 of row-0 and row-2
# A 'view' of the underlying data in 'x' is produced; no data is copied
x2 = x[::2, 1] # Starting from the first element going to the end, 
print(f"Indexed Array:\n{x2}\n")

x3= x[x < 0]
print(f"All Negative Elements:\n{x3}")

Original Array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Indexed Array:
[ 2 -3]

All Negative Elements:
[-5 -7 -1 -3 -3]


`x[::2, 1]` checks every two elements (starting with the 0th) and first row.

We will see that, where basic indexing provides us with a *view* of the data within the array without making a copy of it, advanced indexing requires that a copy of the accessed data be made. Here, we will define basic indexing and understand the nuances of working with views of arrays.

# Basic Indexing

## Indexing with Integers and Slice Objects

One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0.

In [3]:
# Accessing the element at ro1-1, last-column of 'x'ArithmeticError
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

print(f"Row-1, last-column of 'x' = {x[1, -1]}\n")

"""
Access the subarray of 'x' contained within the f
irst two rows 
and the first three columns
"""
print(f"First two rows, first three columns of 'x':\n{x[:2, :3]}\n")

"""
NumPy fills in 'trailing' slices if we don't supply as many indices
as there are dimensions in that array.
"""
print(x[0])

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Row-1, last-column of 'x' = 8

First two rows, first three columns of 'x':
[[-5  2  0]
 [-1  9  3]]

[-5  2  0 -7]


Recall that the familiar slicing syntax actually forms `slice` objects "behind the scenes":

In [4]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

# Equivalent to x[:2, :3]
x[slice(None, 2)], slice(None, 3)

(array([[-5,  2,  0, -7],
        [-1,  9,  3,  8]]),
 slice(None, 3, None))

# Using a Tuple as an N-Dimensional Index

According to its definition, we must supply our array-indices as a tuple in order to invoke basic indexing.

As it turns out, we have been forming tuples of indices all along! That is, every time that we index into an array using the syntax `x[i, j, k]`, we are actually forming a tuple containing those indices. That is, `x[i, j, k]` is equivalent to `x[(i, j, k)]`

`x[i, j, k]` forms the tuple `(i, j, k)` and passes that to the array's "get-item" mechanism. Thus, `x[0, 3]` is equivalent to `x[(0, 3)]`.

In [5]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
N-dimensional indexing utilizes tuples:
'x[i, k, k]' is equivalent to 'x[(i, j, k)]'
"""

print(f"Result without tuple notation: {x[1, -1]}")
print(f"Result with tuple notation: {x[(1, -1)]}\n")

# Equivalent: x[:2, :3]
print(f"Slice method results:\n{x[(slice(None, 2), slice(None, 3))]}\n")

# Equivalent: x[0]
print(f"x[(0,)] results:\n {x[(0,)]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Result without tuple notation: 8
Result with tuple notation: 8

Slice method results:
[[-5  2  0]
 [-1  9  3]]

x[(0,)] results:
 [-5  2  0 -7]


All objects used in this "get-item" syntax are packed into a tuple. For instance, `x[0, (0, 1)]` is equivalent to `x[(0, (0, 1))]`.

You may be surprised to find that this is a valid index. However, see that it does **not invoke basic indexing**; the index used here is a tuple that contains an integer and *another tuple*, which is not permitted by the rules of basic indexing.

Finally, not that the rules of basic indexing specifically call for a tuple of indices. Supplying a list of indices triggers advanced indexing rather than basic indexing.

In [6]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])
print(f"Original array:\n{x}\n")

print("Basic indexing result using x[(1, -1)]:")
print(x[(1, -1)])
print()
print(f"Advanced indexing result using x[[1, -1]]:")
print(x[[1, -1]])

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Basic indexing result using x[(1, -1)]:
8

Advanced indexing result using x[[1, -1]]:
[[-1  9  3  8]
 [-3 -3  4  6]]


# Elipsis and Newaxis Objects

The `np.newaxis` object can be passed as an index to an array, in order to insert a size-1 dimension into the array:

In [7]:
import numpy as np

x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

# Inserting size-1 dimensions with `np.newaxis`
x1 = x[np.newaxis, :, :, np.newaxis]

# Forming the index as an explicit tuple
x2 = x[(np.newaxis, slice(None), slice(None), np.newaxis)]

print(x1)
print(x1.shape)
print()
print(x2)
print(x2.shape)

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

[[[[-5]
   [ 2]
   [ 0]
   [-7]]

  [[-1]
   [ 9]
   [ 3]
   [ 8]]

  [[-3]
   [-3]
   [ 4]
   [ 6]]]]
(1, 3, 4, 1)

[[[[-5]
   [ 2]
   [ 0]
   [-7]]

  [[-1]
   [ 9]
   [ 3]
   [ 8]]

  [[-3]
   [-3]
   [ 4]
   [ 6]]]]
(1, 3, 4, 1)


We can also use the built-in `Elipsis` object to insert slices into our index such that the index has as many entries as the array has dimensions. In the same way that `:` can be used to represent a `slice` object, `...` can be used to represent an `Elipsis` object:

In [8]:
y = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7]],

              [[ 8,  9, 10, 11],
               [12, 13, 14, 15]],

              [[16, 17, 18, 19],
               [20, 21, 22, 23]]])

# equivalent" `y[:, :, 0]`
print(y[..., 0])

print()

# using an explicit tuple
print(y[(Ellipsis, 0)])

print()

# equivalent: `y[0, :, 1]`
print(y[1, ..., 1])

# apply to all dimensions
print(y[:, :, 1])

[[ 0  4]
 [ 8 12]
 [16 20]]

[[ 0  4]
 [ 8 12]
 [16 20]]

[ 9 13]
[[ 1  5]
 [ 9 13]
 [17 21]]


An index cannot possess more than one `Elipsis` entry. This can be extremely useful when working with arrays of varying dimensionalities. To access column-0 along all dimensions of an array, `z`, would look like `z[:, 0]` for a 2D array, `z[:, :, 0]` for a 3D array, and so on. `z[..., 0]` succinctly encapsulates all iterations of this.

# Producing a View of an Array

As stated above, using basic indexing does not return a copy of the data being accessed. Rather, it produces a *view* of the underlying data. NumPy provides the function `np.shares_memory` to determine if the two arrays refer to the same underlying data.

In [9]:
z = np.array([[ 3.31,  4.71,  0.4 ],
              [ 0.21,  2.85,  3.21],
              [-3.77,  4.53, -1.15]])

subarray = z[:, 0]
subarray # A view of the array data referenced by `z`

np.shares_memory(subarray, z)


True

A single number returned by basic indexing does not share memory with the parent array:

In [10]:
z = np.array([[ 3.31,  4.71,  0.4 ],
              [ 0.21,  2.85,  3.21],
              [-3.77,  4.53, -1.15]])

z[0, 0]
np.shares_memory(z[0, 0], z)


False

The function `np.copy` can be used to create a copy of an array, such that it no longer shares memory with any other array.

In [11]:
new_subarray = np.copy(subarray)
new_subarray
np.shares_memory(new_subarray, z)

False

Utilizing an array in a mathematical expression involving arithmetic operators returns an entirely distinct array that doesn't share memory with the original array.

In [12]:
np.shares_memory(subarray + 2, subarray)

False

Thus, updating a variable `subarray` via `subarray = subarray + 2` does not overwrite the original data referenced by `subarray`. Rather, `subarray + 2` assigns that new array to the variable `subarray`.

NumPy does provide mechanisms for performing mathematical operations to directly update the underlying data of an array without having to create a distinct array. We will discuss these mechanisms in the next subsection.

Given:

In [13]:
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

Which of the following expressions create views of `x`? That is, in which cases do `x` and the created variable reference the same underlying array data? Check your work using `np.shares_memory`.

In [14]:
a1 = x
np.shares_memory(a1, x)

True