# Insert a New Axis Within a NumPy Array

NumPy provides us with two different built-in functions to increase the dimension of an array.

# np.newaxis()

The `np.newaxis()` object is equivalent to using `None` as a parameter while declaring the array. The trick is to use the `np.newaxis` object as a parameter at the index location in which you want to add the new axis.

In this example, the code uses NumPy to create a 2-D array with shape (5, 5) containing sequential values. It then transforms the array into a 5-D array by adding dimensions using indexing with `np.newaxis`. The resulting shape is (1, 5, 5, 1, 1).

In [9]:
import numpy as np

arr = np.arange(5*5)
print(arr)

print()

arr = arr.reshape(5, 5)
print(arr)

print()

print(arr.shape)

arr_5d = arr[np.newaxis, ..., np.newaxis, np.newaxis]
print(arr_5d)
print(arr_5d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

(5, 5)
[[[[[ 0]]

   [[ 1]]

   [[ 2]]

   [[ 3]]

   [[ 4]]]


  [[[ 5]]

   [[ 6]]

   [[ 7]]

   [[ 8]]

   [[ 9]]]


  [[[10]]

   [[11]]

   [[12]]

   [[13]]

   [[14]]]


  [[[15]]

   [[16]]

   [[17]]

   [[18]]

   [[19]]]


  [[[20]]

   [[21]]

   [[22]]

   [[23]]

   [[24]]]]]
(1, 5, 5, 1, 1)


Simply put, `np.newaxis` is used to increase the dimension of the existing array by one or more dimension. Thus,

- 1D array will become 2D array
- 2D array will become 3D array
- 3D array will become 4D array
- 4D array will become 5D array

and so on.

Example:

In [18]:
arr = np.array([2, 0, 1, 8])
arr1 = arr[np.newaxis, :]
arr2 = arr[:, np.newaxis]

print(f"Unedited array:{arr}")
print()
print(arr1)
print()
print(arr2)
print()
print(arr1.shape)
print(arr2.shape)

Unedited array:[2 0 1 8]

[[2 0 1 8]]

[[2]
 [0]
 [1]
 [8]]

(1, 4)
(4, 1)
