# numpy.pad() Function

`numpy.pad()` is used to pad the NumPy arrays. The function returns the padded array of rank equal to the given array and the shape will increase according to `pad_width`.

In [1]:
import numpy as np

print(np.info(np.pad))

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
    for each axis.
    ``(before, after)`` or ``((before, after),)`` yields same before
    and after pad for each axis.
    ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
    for all axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'media

In [ ]:
import numpy as np

# Pad array using CONSTANT mode

arr = [1,3,2,5,4]
pad_arr = np.pad(arr, (3,2), "constant", constant_values=(6,4))
print(pad_arr)

[6 6 6 1 3 2 5 4 4 4]


In [3]:
import numpy as np

# Pad array using 'linear_ramp' mode

arr = [1,3,2,5,4]

pad_arr = np.pad(arr, (3, 2), "linear_ramp", end_values=(-4, 5))

print(pad_arr)

[-4 -3 -1  1  3  2  5  4  4  5]


In [4]:
import numpy as np

# Pad array using 'maximum' mode


arr = [1,3,9,5,4]
pad_arr = np.pad(arr, (3,), "maximum")
print(pad_arr)

[9 9 9 1 3 9 5 4 9 9 9]
