# Random Permutations of Elements

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: `shuffle()` and `permutation()`.

# Shuffling Arrays

Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

Randomly shuffle elements of the following array:

In [1]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)

print(arr)

[3 5 4 1 2]


The `shuffle()` method makes changes to the original array.

# Generating Permutation of Arrays

Generate a random permutation of elements of the following array:

In [8]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 5 4 2 1]


I wanna see if I can do it a slightly different way:

In [6]:
from numpy import random
import numpy as np

arr = random.permutation(np.array([1,2,3,4,5]))

print(arr)

[1 4 2 3 5]


Probably better to assign the array beforehand though.

The `permutation()` method returns a re-arranged array and leaves the original unchanged.