One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0.

In [10]:
import numpy as np

x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
Access the column-1 of row-0 and row0-2
This is an example of basic indexing
Creates a 'view' of the underlying data in `x` is produced. No data is copied
"""
print(f"Basic Indexing: Access column-1, row-0, and row-2:\n{x[::2,1]}\n")

"""
An example of advanced indexing
Access all negative elements in `x`
This produces a copy of the accessed data
"""
print(f"Advanced Indexing: Access all negative elements:\n{x[x < 0]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Basic Indexing: Access column-1, row-0, and row-2:
[ 2 -3]

Advanced Indexing: Access all negative elements:
[-5 -7 -1 -3 -3]


We will see that, where basic indexing provides us with a *view* of the data within the array without making a copy of it, advanced indexing requires that a copy of the accessed data be made.

Here, we will define basic indexing and understand the nuances of working with views of arrays.

# Basic Indexing

**Definition:**

Given an *N*-dimensional array, `x`, `x[index]` invokes **basic indexing** whenever `index` is a *tuple* containing any combination of the following types of objects:

- integers
- slice objects
- Ellipsis objects
- numpy.newaxis objects

Accessing the contents of an array via basic indexing **does not create a copy** of those contents. Rather, a "view" of the same underlying data is produced.

## Indexing with Integers and Slice Objects

One can access an individual element or a "subsection" of an *N*-dimensional array by specifying *N* integers or slice-objects, or a combination of the two.

When supplied fewer-than *N* indices, NumPy will automatically "fill-in" the remaining indices with trailing slices.

In [21]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
Accessing the element located at row-1, last-column of `x`
"""
print(f"Access the element located at row-1, last-column of `x`:\n{x[1, -1]}\n")

"""
Access the subarray of `x` contained within the first two rows
and the first three columns
"""

print(f"Access the subarray of `x` contained within the first two columns\nand the first three columns:\n{x[:2, :3]}\n")

"""
NumPy fills-in 'trailing' slices if we don't supply as many indices
as there are dimensions in the given array
"""
print(f"Filling-in 'trailing' slices when there are less indices\nthan dimensions in the given array:\n{x[0]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Access the element located at row-1, last-column of `x`:
8

Access the subarray of `x` contained within the first two columns
and the first three columns:
[[-5  2  0]
 [-1  9  3]]

Filling-in 'trailing' slices when there are less indices
than dimensions in the given array:
[-5  2  0 -7]


**Note:** The slice `x[:2, :3]` starts from row and column 0, but **does not** include index 2 and 3.

Also, recall that the *slicing* syntax forms `slice` objects "behind the scenes":

In [22]:
print(x[slice(None, 2), slice(None, 3)])

[[-5  2  0]
 [-1  9  3]]


# Why use slice()?

You use `slice()` for very specific instances when you need variables or dynamic slicing.

Colon Syntax, on the other hand, is concise, readable, and is basically what you'll be using 90% of the time.

# Using a Tuple as an N-dimensional Index

According to its definition, we must supply our array-indices as a tuple in order to invoke basic indexing. As it turns out, we have been forming tuple indices all along!

That is, every time that we index into an array using the syntax `x[i, j, k]`, we are actually forming a *tuple* containing those indices. That is, `x[i, j, k]` us equivalent to `x[(i, j, k )]`.

`x[i, j, k]` forms the tuple `(i, j, k)` and passes that to the array's "get-item" mechanism. Thus, `x[0, 3]` is equivalent to `x[(0, 3)]`.

In [ ]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

"""
N-dimensional indexing utilizes tuples:
`x[i, j, k]` is equivalent to `x[(i, j, k)]`
"""
print(f"Tuple result: {x[(1, -2)]}\n")

# equivalent: x[1, -1]
print(f"Indexing result: {x[1, -1]}\n")

# equivalent: x[:2, :3]
print(f"Using slice() method:\n{x[(slice(None, 2), slice(None, 3))]}\n")

# equivalent: x[0]
print(f"Print the first row using a tuple:\n{x[(0,)]}")l

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Tuple result: 3

Indexing result: 8

Using slice() method:
[[-5  2  0]
 [-1  9  3]]

Print the first row using a tuple:
[-5  2  0 -7]
<class 'numpy.ndarray'>


All objects used in this "get-item" syntax are packed into a tuple. For instance, `x[0, (0, 1)]` is equivalent to `x[(0, (0,1))]`. You may be surprised to find that this is a valid index. However, see that it **does not invoke basic indexing**; the index used here is a tuple that contains an integer and another tuple, which is not permitted by the rules of basic indexing.

Finally, note that the rules of basic indexing specifically call for a *tuple* of indices. Supplying a list of indices triggers advanced indexing rather than basic indexing!

In [36]:
x = np.array([[-5, 2, 0, -7],
              [-1, 9, 3, 8],
              [-3, -3, 4, 6]])

print(f"Original array:\n{x}\n")

# Basic indexing specifically requires a tuple
print(f"Basic indexing with a tuple:\n{x[(1, -1)]}\n")

# Indexing with a list triggers advanced indexing
print(f"Advanced indexing with a list:\n{x[[1, -1]]}")

Original array:
[[-5  2  0 -7]
 [-1  9  3  8]
 [-3 -3  4  6]]

Basic indexing with a tuple:
8

Advanced indexing with a list:
[[-1  9  3  8]
 [-3 -3  4  6]]
